# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u9508/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/u9508/proprietary/bin/akm8975:system/bin/akm8975 \
    vendor/huawei/u9508/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/huawei/u9508/proprietary/bin/atcmdserver:system/bin/atcmdserver \
    vendor/huawei/u9508/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/huawei/u9508/proprietary/bin/glgps:system/bin/glgps \
    vendor/huawei/u9508/proprietary/bin/gpsatnewfilter:system/bin/gpsatnewfilter \
    vendor/huawei/u9508/proprietary/bin/gpslogd:system/bin/gpslogd \
    vendor/huawei/u9508/proprietary/bin/hci_dev_state:system/bin/hci_dev_state \
    vendor/huawei/u9508/proprietary/bin/IMCdownload_App:system/bin/IMCdownload_App \
    vendor/huawei/u9508/proprietary/bin/imc_poweron:system/bin/imc_poweron \
    vendor/huawei/u9508/proprietary/bin/Injection_nv:system/bin/Injection_nv \
    vendor/huawei/u9508/proprietary/bin/ntfs-3g:system/bin/ntfs-3g \
    vendor/huawei/u9508/proprietary/bin/nvm_server:system/bin/nvm_server \
    vendor/huawei/u9508/proprietary/bin/rild:system/bin/rild \
    vendor/huawei/u9508/proprietary/bin/vold:system/bin/vold \
    vendor/huawei/u9508/proprietary/etc/bluetooth/BCM4330.hcd:system/etc/bluetooth/BCM4330.hcd \
    vendor/huawei/u9508/proprietary/lib/egl/libEGL_VIVANTE.so:system/lib/egl/libEGL_VIVANTE.so \
    vendor/huawei/u9508/proprietary/lib/egl/libGLESv1_CM_VIVANTE.so:system/lib/egl/libGLESv1_CM_VIVANTE.so \
    vendor/huawei/u9508/proprietary/lib/egl/libGLESv2_VIVANTE.so:system/lib/egl/libGLESv2_VIVANTE.so \
    vendor/huawei/u9508/proprietary/lib/helix:system/lib/helix \
    vendor/huawei/u9508/proprietary/lib/helix/asfff.so:system/lib/helix/asfff.so \
    vendor/huawei/u9508/proprietary/lib/helix/asxff.so:system/lib/helix/asxff.so \
    vendor/huawei/u9508/proprietary/lib/helix/asxrender.so:system/lib/helix/asxrender.so \
    vendor/huawei/u9508/proprietary/lib/helix/atrc.so:system/lib/helix/atrc.so \
    vendor/huawei/u9508/proprietary/lib/helix/audplin.so:system/lib/helix/audplin.so \
    vendor/huawei/u9508/proprietary/lib/helix/authmgr.so:system/lib/helix/authmgr.so \
    vendor/huawei/u9508/proprietary/lib/helix/clntxres.so:system/lib/helix/clntxres.so \
    vendor/huawei/u9508/proprietary/lib/helix/colorcvt.so:system/lib/helix/colorcvt.so \
    vendor/huawei/u9508/proprietary/lib/helix/cook.so:system/lib/helix/cook.so \
    vendor/huawei/u9508/proprietary/lib/helix/cvt1.so:system/lib/helix/cvt1.so \
    vendor/huawei/u9508/proprietary/lib/helix/drv2.so:system/lib/helix/drv2.so \
    vendor/huawei/u9508/proprietary/lib/helix/drvc.so:system/lib/helix/drvc.so \
    vendor/huawei/u9508/proprietary/lib/helix/dtdrplin.so:system/lib/helix/dtdrplin.so \
    vendor/huawei/u9508/proprietary/lib/helix/hxdtdriver.so:system/lib/helix/hxdtdriver.so \
    vendor/huawei/u9508/proprietary/lib/helix/hxltcolor.so:system/lib/helix/hxltcolor.so \
    vendor/huawei/u9508/proprietary/lib/helix/hxmedpltfm.so:system/lib/helix/hxmedpltfm.so \
    vendor/huawei/u9508/proprietary/lib/helix/hxmedplyeng.so:system/lib/helix/hxmedplyeng.so \
    vendor/huawei/u9508/proprietary/lib/helix/hxnetwksvc.so:system/lib/helix/hxnetwksvc.so \
    vendor/huawei/u9508/proprietary/lib/helix/hxsdp.so:system/lib/helix/hxsdp.so \
    vendor/huawei/u9508/proprietary/lib/helix/hxxml.so:system/lib/helix/hxxml.so \
    vendor/huawei/u9508/proprietary/lib/helix/nullrend.so:system/lib/helix/nullrend.so \
    vendor/huawei/u9508/proprietary/lib/helix/omxv.so:system/lib/helix/omxv.so \
    vendor/huawei/u9508/proprietary/lib/helix/raac.so:system/lib/helix/raac.so \
    vendor/huawei/u9508/proprietary/lib/helix/ralf.so:system/lib/helix/ralf.so \
    vendor/huawei/u9508/proprietary/lib/helix/ramfformat.so:system/lib/helix/ramfformat.so \
    vendor/huawei/u9508/proprietary/lib/helix/ramrender.so:system/lib/helix/ramrender.so \
    vendor/huawei/u9508/proprietary/lib/helix/rarender.so:system/lib/helix/rarender.so \
    vendor/huawei/u9508/proprietary/lib/helix/rmfformat.so:system/lib/helix/rmfformat.so \
    vendor/huawei/u9508/proprietary/lib/helix/rn5auth.so:system/lib/helix/rn5auth.so \
    vendor/huawei/u9508/proprietary/lib/helix/rv20.so:system/lib/helix/rv20.so \
    vendor/huawei/u9508/proprietary/lib/helix/rv30.so:system/lib/helix/rv30.so \
    vendor/huawei/u9508/proprietary/lib/helix/rv40.so:system/lib/helix/rv40.so \
    vendor/huawei/u9508/proprietary/lib/helix/rvrender.so:system/lib/helix/rvrender.so \
    vendor/huawei/u9508/proprietary/lib/helix/sipr.so:system/lib/helix/sipr.so \
    vendor/huawei/u9508/proprietary/lib/helix/smlfformat.so:system/lib/helix/smlfformat.so \
    vendor/huawei/u9508/proprietary/lib/helix/smlrender.so:system/lib/helix/smlrender.so \
    vendor/huawei/u9508/proprietary/lib/helix/smplfsys.so:system/lib/helix/smplfsys.so \
    vendor/huawei/u9508/proprietary/lib/helix/vidplin.so:system/lib/helix/vidplin.so \
    vendor/huawei/u9508/proprietary/lib/helix/vidsite.so:system/lib/helix/vidsite.so \
    vendor/huawei/u9508/proprietary/lib/helix/wm9v.so:system/lib/helix/wm9v.so \
    vendor/huawei/u9508/proprietary/lib/helix/wma9.so:system/lib/helix/wma9.so \
    vendor/huawei/u9508/proprietary/lib/helix/wmaA.so:system/lib/helix/wmaA.so \
    vendor/huawei/u9508/proprietary/lib/helix/wmarender.so:system/lib/helix/wmarender.so \
    vendor/huawei/u9508/proprietary/lib/helix/wmerender.so:system/lib/helix/wmerender.so \
    vendor/huawei/u9508/proprietary/lib/helix/wmp4.so:system/lib/helix/wmp4.so \
    vendor/huawei/u9508/proprietary/lib/helix/wmv8.so:system/lib/helix/wmv8.so \
    vendor/huawei/u9508/proprietary/lib/helix/wmv9.so:system/lib/helix/wmv9.so \
    vendor/huawei/u9508/proprietary/lib/helix/wmvrender.so:system/lib/helix/wmvrender.so \
    vendor/huawei/u9508/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    vendor/huawei/u9508/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/huawei/u9508/proprietary/lib/hw/audio_policy.k3v2oem1.so:system/lib/hw/audio_policy.k3v2oem1.so \
    vendor/huawei/u9508/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/huawei/u9508/proprietary/lib/hw/audio.primary.k3v2oem1.so:system/lib/hw/audio.primary.k3v2oem1.so \
    vendor/huawei/u9508/proprietary/lib/hw/camera.k3v2oem1.so:system/lib/hw/camera.k3v2oem1.so \
    vendor/huawei/u9508/proprietary/lib/hw/copybit.huawei.so:system/lib/hw/copybit.huawei.so \
    vendor/huawei/u9508/proprietary/lib/hw/gps.k3v2oem1.so:system/lib/hw/gps.k3v2oem1.so \
    vendor/huawei/u9508/proprietary/lib/hw/gralloc.huawei.so:system/lib/hw/gralloc.huawei.so \
    vendor/huawei/u9508/proprietary/lib/hw/hwcomposer.huawei.so:system/lib/hw/hwcomposer.huawei.so \
    vendor/huawei/u9508/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
    vendor/huawei/u9508/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
    vendor/huawei/u9508/proprietary/lib/hw/sensors.k3v2oem1.so:system/lib/hw/sensors.k3v2oem1.so \
    vendor/huawei/u9508/proprietary/lib/libhuawei-audio-ril.so:system/lib/libhuawei-audio-ril.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_asf_extractor.so:system/lib/lib_k3_asf_extractor.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_avi_extractor.so:system/lib/lib_k3_avi_extractor.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_extractor_utils.so:system/lib/lib_k3_extractor_utils.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_flv_extractor.so:system/lib/lib_k3_flv_extractor.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_generic_audio_extractor.so:system/lib/lib_k3_generic_audio_extractor.so \
    vendor/huawei/u9508/proprietary/lib/libk3jpeg.so:system/lib/libk3jpeg.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_m2ts_extractor.so:system/lib/lib_k3_m2ts_extractor.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_mov_extractor.so:system/lib/lib_k3_mov_extractor.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_mpg_extractor.so:system/lib/lib_k3_mpg_extractor.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_omx_avcenc.so:system/lib/lib_k3_omx_avcenc.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_omx_avc.so:system/lib/lib_k3_omx_avc.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_omxcore.so:system/lib/lib_k3_omxcore.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_omx_mpeg2.so:system/lib/lib_k3_omx_mpeg2.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_omx_mpeg4.so:system/lib/lib_k3_omx_mpeg4.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_omx_rv.so:system/lib/lib_k3_omx_rv.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_omx_vc1.so:system/lib/lib_k3_omx_vc1.so \
    vendor/huawei/u9508/proprietary/lib/lib_k3_omx_vp8.so:system/lib/lib_k3_omx_vp8.so \
    vendor/huawei/u9508/proprietary/lib/libnv_public_interface.so:system/lib/libnv_public_interface.so \
    vendor/huawei/u9508/proprietary/lib/liboeminfo_public_interface.so:system/lib/liboeminfo_public_interface.so \
    vendor/huawei/u9508/proprietary/lib/liboeminfo.so:system/lib/liboeminfo.so \
    vendor/huawei/u9508/proprietary/lib/libparseprofile.so:system/lib/libparseprofile.so \
    vendor/huawei/u9508/proprietary/lib/libRedEye.so:system/lib/libRedEye.so \
    vendor/huawei/u9508/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/huawei/u9508/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/huawei/u9508/proprietary/lib/libxgold-ril.so:system/lib/libxgold-ril.so \
    vendor/huawei/u9508/proprietary/vendor/firmware:system/vendor/firmware \
    vendor/huawei/u9508/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:system/vendor/firmware/fw_bcmdhd_apsta.bin \
    vendor/huawei/u9508/proprietary/vendor/firmware/fw_bcmdhd.bin:system/vendor/firmware/fw_bcmdhd.bin \
    vendor/huawei/u9508/proprietary/vendor/firmware/fw_bcmdhd_p2p.bin:system/vendor/firmware/fw_bcmdhd_p2p.bin \
    vendor/huawei/u9508/proprietary/vendor/firmware/fw_bcmdhd_test.bin:system/vendor/firmware/fw_bcmdhd_test.bin \
    vendor/huawei/u9508/proprietary/vendor/firmware/nvram.txt:system/vendor/firmware/nvram.txt \
    vendor/huawei/u9508/proprietary/xbin/acceleratord:system/xbin/acceleratord \
    vendor/huawei/u9508/proprietary/xbin/athena:system/xbin/athena \
    vendor/huawei/u9508/proprietary/isp.bin:system/isp.bin \
    vendor/huawei/u9508/proprietary/ons.bin:system/ons.bin \
    vendor/huawei/u9508/proprietary/lib/lib_8290.so:system/lib/lib_8290.so \
    vendor/huawei/u9508/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/huawei/u9508/proprietary/lib/libcamera_core.so:system/lib/libcamera_core.so \
    vendor/huawei/u9508/proprietary/lib/libcamera_scalado.so:system/lib/libcamera_scalado.so \
    vendor/huawei/u9508/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
    vendor/huawei/u9508/proprietary/lib/libimageinfo.so:system/lib/libimageinfo.so \
    vendor/huawei/u9508/proprietary/lib/libGAL.so:system/lib/libGAL.so \
    vendor/huawei/u9508/proprietary/lib/liboverlay.so:system/lib/liboverlay.so \
    vendor/huawei/u9508/proprietary/lib/lib_g1.so:system/lib/lib_g1.so \
    vendor/huawei/u9508/proprietary/lib/libGLSLC.so:system/lib/libGLSLC.so \
    vendor/huawei/u9508/proprietary/lib/libgnuexif.so:system/lib/libgnuexif.so \
    vendor/huawei/u9508/proprietary/lib/libdenoise.so:system/lib/libdenoise.so \
    vendor/huawei/u9508/proprietary/lib/libmrc_cg_postprocess.so:system/lib/libmrc_cg_postprocess.so \
    vendor/huawei/u9508/proprietary/lib/liblocSDK_2.4.so:system/lib/liblocSDK_2.4.so \
    vendor/huawei/u9508/proprietary/lib/liblocSDK_2_5OEM.so:system/lib/liblocSDK_2_5OEM.so \
    vendor/huawei/u9508/proprietary/lib/libom.so:system/lib/libom.so \
    vendor/huawei/u9508/proprietary/lib/libbcm_fm_power.so:system/lib/libbcm_fm_power.so \
    vendor/huawei/u9508/proprietary/lib/libbcm_gps_pdttest.so:system/lib/libbcm_gps_pdttest.so \
    vendor/huawei/u9508/proprietary/bin/chargershow:system/bin/chargershow \
    vendor/huawei/u9508/proprietary/bin/chargeservice:system/bin/chargeservice \
    vendor/huawei/u9508/proprietary/bin/hdmi_daemon:system/bin/hdmi_daemon \
    vendor/huawei/u9508/proprietary/bin/diagserver:system/bin/diagserver \
    vendor/huawei/u9508/proprietary/lib/libchip_management.so:system/lib/libchip_management.so \
    vendor/huawei/u9508/proprietary/lib/libnve.so:system/lib/libnve.so \
    vendor/huawei/u9508/proprietary/lib/libsurfaceflinger_client.so:system/lib/libsurfaceflinger_client.so \
    vendor/huawei/u9508/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/huawei/u9508/proprietary/bin/pcscd:system/bin/pcscd \
#    vendor/huawei/u9508/proprietary/lib/libvpp.so:system/lib/libvpp.so \
